# Generated by Django 5.2.8 on 2026-03-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
