# Generated by Django 5.2.8 on 2026-03-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='ano',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='categoria',
            field=models.CharField(blank=True, choices=[('SUV', 'SUV'), ('SEDAN', 'Sedan'), ('HATCH', 'Hatch'), ('PICAPE', 'Picape'), ('ESPORTE', 'Esportivo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='combustivel',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='consumo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='potencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
